//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainResApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int cancellation_id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public Nullable<System.DateTime> cancellation_date { get; set; }
        public Nullable<decimal> cancellation_charges { get; set; }
        public Nullable<decimal> refund_amount { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
