//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainResApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Cancellations = new HashSet<Cancellation>();
        }
    
        public int reservation_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public Nullable<int> seat_id { get; set; }
        public string pnr_number { get; set; }
        public int number_of_passengers { get; set; }
        public decimal total_fare { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> booked_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancellation> Cancellations { get; set; }
        public virtual Train_Schedules Train_Schedules { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual User User { get; set; }
    }
}
